version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
build_script:
  - cmd: dotnet test
test: off
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true
